<p id="detail" class="pre">[RuntimeException: Exception thrown in sub-project-inside]</p>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="1"><span class="line">1</span><span class="code">package inside;</span></pre>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="2"><span class="line">2</span><span class="code"></span></pre>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="3"><span class="line">3</span><span class="code">public class Foo {</span></pre>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="4"><span class="line">4</span><span class="code">    public static void fail() {</span></pre>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="5" ><span class="line">5</span><span class="code">        throw new RuntimeException(&quot;Exception thrown in sub-project-inside&quot;);</span></pre>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="6"><span class="line">6</span><span class="code">    }</span></pre>
/modules/sub-project-inside/src/main/scala/Foo.java" data-line="7"><span class="line">7</span><span class="code">}</span></pre>
